import { saveSettingsAction } from "@/app/actions";
import { ActionForm } from "@/components/action-form";
import { Card, Shell } from "@/components/shell";
import { shellUser } from "@/lib/auth";
import { getDashboard } from "@/lib/queries";

export default async function SettingsPage() {
  const { settings, context } = await getDashboard();
  return <Shell title="Fee model and thresholds" user={shellUser(context)}><Card><p className="mb-5 text-sm text-slate-500">These defaults apply whenever Etsy does not provide the actual fee in an export.</p><ActionForm action={saveSettingsAction} submitLabel="Save settings" className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><label>Shop / workspace name</label><input name="workspaceName" defaultValue={context.workspace.name} required maxLength={80} /></div><div><label>Hourly labor rate</label><input name="hourlyRate" type="number" step="0.01" defaultValue={settings.hourlyRate} /></div><div><label>Listing fee per unit</label><input name="listingFee" type="number" step="0.01" defaultValue={settings.listingFee} /></div><div><label>Transaction fee %</label><input name="transactionRate" type="number" step="0.1" defaultValue={settings.transactionRate} /></div><div><label>Payment processing %</label><input name="paymentRate" type="number" step="0.1" defaultValue={settings.paymentRate} /></div><div><label>Payment fixed fee</label><input name="paymentFixed" type="number" step="0.01" defaultValue={settings.paymentFixed} /></div><div><label>Offsite ads rate %</label><input name="offsiteAdsRate" type="number" step="0.1" defaultValue={settings.offsiteAdsRate} /></div><div><label>Estimated % orders via offsite ads</label><input name="estimatedOffsitePercent" type="number" step="1" defaultValue={settings.estimatedOffsitePercent} /><p className="mt-1 text-xs text-slate-500">Used only when no order is manually flagged.</p></div><div><label>Default shipping cost per order</label><input name="defaultShippingCost" type="number" step="0.01" defaultValue={settings.defaultShippingCost} /></div><div><label>Red margin threshold %</label><input name="marginThreshold" type="number" step="1" defaultValue={settings.marginThreshold} /></div><div><label>Target margin %</label><input name="targetMargin" type="number" step="1" defaultValue={settings.targetMargin} /></div><label className="flex items-center gap-2 sm:col-span-2"><input className="h-4 w-4" name="offsiteAdsEnabled" type="checkbox" defaultChecked={settings.offsiteAdsEnabled} /> Include offsite ads in true profit</label></ActionForm></Card></Shell>;
}
