import Link from "next/link";
import { saveProductAction } from "@/app/actions";
import { ActionForm } from "@/components/action-form";
import { hasMissingCosts } from "@/components/onboarding";
import { Card, Notice, Shell } from "@/components/shell";
import { shellUser } from "@/lib/auth";
import { getDashboard } from "@/lib/queries";

export default async function ProductsPage({ searchParams: searchParamsPromise }: { searchParams: Promise<{ imported?: string; items?: string }> }) {
  const searchParams = await searchParamsPromise;
  const { products, context } = await getDashboard();
  const totalUnits = products.reduce((sum, product) => sum + product.units, 0);
  const missingCosts = products.filter(hasMissingCosts).length;
  const imported = Number(searchParams.imported);
  return <Shell title="Products and costs" user={shellUser(context)}>
    {Number.isFinite(imported) && imported > 0 && <Notice kind="success">Imported {imported.toLocaleString()} orders{searchParams.items ? ` and ${Number(searchParams.items).toLocaleString()} line items` : ""}. <Link href="/app" className="font-semibold underline">See your dashboard →</Link>{missingCosts ? <> Profit after Etsy fees and shipping is ready now. Optionally add material and labor costs for <strong>{missingCosts} product{missingCosts === 1 ? "" : "s"}</strong> below to see your full margin.</> : null}</Notice>}
    {!imported && missingCosts > 0 && <Notice kind="info">{missingCosts} product{missingCosts === 1 ? " shows" : "s show"} profit after Etsy fees and shipping only (highlighted). Even a rough material cost makes the margin real — start with your best sellers.</Notice>}
    <Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Cost data</h2><p className="text-sm text-ink-500">Optional. Fill in your top sellers first — TrueMargin applies each cost to every unit you sold. Leave a product blank and it shows profit after Etsy fees and shipping only.</p></div><Link href="/app/import" className="text-xs font-semibold text-brand-700">Import more →</Link></div><div className="mt-4 space-y-4">{products.map((product) => <ActionForm action={saveProductAction} key={product.id} submitLabel="Save" inline submitClassName="rounded-lg bg-brand-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50" className={`grid gap-3 rounded-xl border p-4 md:grid-cols-[1.5fr_0.8fr_0.7fr_0.7fr_0.7fr_0.7fr_0.7fr_auto] md:items-end ${hasMissingCosts(product) ? "border-amber-300 bg-amber-50/40" : "border-ink-100"}`}><input type="hidden" name="id" value={product.id} /><div><label className="flex items-center justify-between">Name <Link href={`/app/products/${product.id}`} className="text-[11px] font-semibold text-brand-700">Profit &amp; what-if →</Link></label><input name="name" defaultValue={product.name} required maxLength={200} /></div><div><label>SKU</label><input name="sku" defaultValue={product.sku} maxLength={100} /></div><div><label>Material $</label><input name="materialCost" type="number" min="0" step="any" defaultValue={product.materialCost} /></div><div><label>Labor min</label><input name="laborMinutes" type="number" min="0" defaultValue={product.laborMinutes} /></div><div><label>Packaging $</label><input name="packagingCost" type="number" min="0" step="any" defaultValue={product.packagingCost} /></div><div><label>Stock</label><input name="stockOnHand" type="number" min="0" defaultValue={product.stockOnHand} /></div><div><label>Reorder at</label><input name="reorderPoint" type="number" min="0" defaultValue={product.reorderPoint} /></div></ActionForm>)}{!products.length && <p className="rounded-xl bg-ink-50 p-4 text-sm text-ink-500">Products appear after you load the demo shop or import Etsy Order Items.</p>}</div></Card><Card className="mt-5"><h2 className="font-semibold">Quick product summary</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-ink-500">Products</p><p className="text-2xl font-semibold">{products.length}</p></div><div><p className="text-xs text-ink-500">Units sold</p><p className="text-2xl font-semibold">{totalUnits.toLocaleString()}</p></div><div><p className="text-xs text-ink-500">Missing cost data</p><p className="text-2xl font-semibold">{missingCosts}</p></div></div></Card></Shell>;
}
