import Link from "next/link";
import { saveProductAction } from "@/app/actions";
import { ActionForm } from "@/components/action-form";
import { Card, Shell } from "@/components/shell";
import { shellUser } from "@/lib/auth";
import { getDashboard } from "@/lib/queries";

export default async function ProductsPage() {
  const { products, context } = await getDashboard();
  const totalUnits = products.reduce((sum, product) => sum + product.units, 0);
  const missingCosts = products.filter((product) => product.materialCost === 0 && product.laborMinutes === 0 && product.packagingCost === 0).length;
  return <Shell title="Products and costs" user={shellUser(context)}><Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Cost data</h2><p className="text-sm text-slate-500">Fill these once; TrueMargin applies them to every imported unit.</p></div><Link href="/app/import" className="text-xs font-semibold text-violet-700">Import more →</Link></div><div className="mt-4 space-y-4">{products.map((product) => <ActionForm action={saveProductAction} key={product.id} submitLabel="Save" inline submitClassName="rounded-lg bg-violet-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50" className="grid gap-3 rounded-xl border border-slate-100 p-4 md:grid-cols-[1.5fr_0.8fr_0.7fr_0.7fr_0.7fr_0.7fr_0.7fr_auto] md:items-end"><input type="hidden" name="id" value={product.id} /><div><label>Name</label><input name="name" defaultValue={product.name} required maxLength={200} /></div><div><label>SKU</label><input name="sku" defaultValue={product.sku} maxLength={100} /></div><div><label>Material $</label><input name="materialCost" type="number" min="0" step="0.01" defaultValue={product.materialCost} /></div><div><label>Labor min</label><input name="laborMinutes" type="number" min="0" defaultValue={product.laborMinutes} /></div><div><label>Packaging $</label><input name="packagingCost" type="number" min="0" step="0.01" defaultValue={product.packagingCost} /></div><div><label>Stock</label><input name="stockOnHand" type="number" min="0" defaultValue={product.stockOnHand} /></div><div><label>Reorder at</label><input name="reorderPoint" type="number" min="0" defaultValue={product.reorderPoint} /></div></ActionForm>)}{!products.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Products appear after you load the demo shop or import Etsy Order Items.</p>}</div></Card><Card className="mt-5"><h2 className="font-semibold">Quick product summary</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Products</p><p className="text-2xl font-semibold">{products.length}</p></div><div><p className="text-xs text-slate-500">Units sold</p><p className="text-2xl font-semibold">{totalUnits.toLocaleString()}</p></div><div><p className="text-xs text-slate-500">Missing cost data</p><p className="text-2xl font-semibold">{missingCosts}</p></div></div></Card></Shell>;
}
