import Link from "next/link";
import { saveProductAction } from "@/app/actions";
import { ActionForm } from "@/components/action-form";
import { hasMissingCosts } from "@/components/onboarding";
import { Card, Notice, Shell } from "@/components/shell";
import { shellUser } from "@/lib/auth";
import { getDashboard } from "@/lib/queries";

export default async function ProductsPage({ searchParams: searchParamsPromise }: { searchParams: Promise<{ imported?: string; items?: string }> }) {
  const searchParams = await searchParamsPromise;
  const { products, context } = await getDashboard();
  const totalUnits = products.reduce((sum, product) => sum + product.units, 0);
  const missingCosts = products.filter(hasMissingCosts).length;
  const imported = Number(searchParams.imported);
  return <Shell title="Products and costs" user={shellUser(context)}>
    {Number.isFinite(imported) && imported > 0 && <Notice kind="success">Imported {imported.toLocaleString()} orders{searchParams.items ? ` and ${Number(searchParams.items).toLocaleString()} line items` : ""}. {missingCosts ? <>Now add costs for the <strong>{missingCosts} highlighted product{missingCosts === 1 ? "" : "s"}</strong> below — until then their profit is just revenue minus fees. Then <Link href="/app" className="font-semibold underline">see your dashboard →</Link></> : <Link href="/app" className="font-semibold underline">See your dashboard →</Link>}</Notice>}
    {!imported && missingCosts > 0 && <Notice kind="info">{missingCosts} product{missingCosts === 1 ? " has" : "s have"} no costs yet (highlighted). Even a rough material cost makes the margin numbers real.</Notice>}
    <Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Cost data</h2><p className="text-sm text-slate-500">Fill these once; TrueMargin applies them to every imported unit.</p></div><Link href="/app/import" className="text-xs font-semibold text-violet-700">Import more →</Link></div><div className="mt-4 space-y-4">{products.map((product) => <ActionForm action={saveProductAction} key={product.id} submitLabel="Save" inline submitClassName="rounded-lg bg-violet-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50" className={`grid gap-3 rounded-xl border p-4 md:grid-cols-[1.5fr_0.8fr_0.7fr_0.7fr_0.7fr_0.7fr_0.7fr_auto] md:items-end ${hasMissingCosts(product) ? "border-amber-300 bg-amber-50/40" : "border-slate-100"}`}><input type="hidden" name="id" value={product.id} /><div><label>Name</label><input name="name" defaultValue={product.name} required maxLength={200} /></div><div><label>SKU</label><input name="sku" defaultValue={product.sku} maxLength={100} /></div><div><label>Material $</label><input name="materialCost" type="number" min="0" step="0.01" defaultValue={product.materialCost} /></div><div><label>Labor min</label><input name="laborMinutes" type="number" min="0" defaultValue={product.laborMinutes} /></div><div><label>Packaging $</label><input name="packagingCost" type="number" min="0" step="0.01" defaultValue={product.packagingCost} /></div><div><label>Stock</label><input name="stockOnHand" type="number" min="0" defaultValue={product.stockOnHand} /></div><div><label>Reorder at</label><input name="reorderPoint" type="number" min="0" defaultValue={product.reorderPoint} /></div></ActionForm>)}{!products.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Products appear after you load the demo shop or import Etsy Order Items.</p>}</div></Card><Card className="mt-5"><h2 className="font-semibold">Quick product summary</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Products</p><p className="text-2xl font-semibold">{products.length}</p></div><div><p className="text-xs text-slate-500">Units sold</p><p className="text-2xl font-semibold">{totalUnits.toLocaleString()}</p></div><div><p className="text-xs text-slate-500">Missing cost data</p><p className="text-2xl font-semibold">{missingCosts}</p></div></div></Card></Shell>;
}
