import Link from "next/link";
import { hasMissingCosts, MissingCostsNotice, OnboardingChecklist, onboardingComplete } from "@/components/onboarding";
import { Card, fmtHour, Money, Notice, Shell } from "@/components/shell";
import { shellUser } from "@/lib/auth";
import { getDashboard } from "@/lib/queries";

export default async function DashboardPage({ searchParams: searchParamsPromise }: { searchParams: Promise<{ period?: string; from?: string; to?: string; verified?: string; demo?: string }> }) {
  const searchParams = await searchParamsPromise;
  const data = await getDashboard(searchParams);
  const { totals, products, orders, refunds, settings, context } = data;
  const user = shellUser(context);
  const sorted = [...products].sort((a, b) => a.margin - b.margin);
  const onboarding = { hasOrders: orders.length > 0, productCount: products.length, missingCosts: products.filter(hasMissingCosts).length };
  const byHour = products.filter((product) => product.profitPerHour != null && product.profitPerHour > 0).sort((a, b) => (b.profitPerHour ?? 0) - (a.profitPerHour ?? 0)).slice(0, 5);
  const lowMargin = sorted.filter((product) => product.margin < settings.marginThreshold);
  const reorder = products.filter((product) => product.stockOnHand <= product.reorderPoint);
  return <Shell title="What you actually keep" user={user}>
    {searchParams.verified === "1" && <Notice kind="success">Email confirmed. Your workspace is ready.</Notice>}
    {searchParams.demo === "1" && <Notice kind="success">Demo shop loaded: 202 orders and 16 products. Numbers below are sample data — clear them from your account page when you import your own.</Notice>}
    {!user.subscribed && <Notice kind="error">Your trial has ended. Dashboards stay visible, but imports and edits are paused until you <Link href="/app/billing" className="font-semibold underline">start a subscription</Link>.</Notice>}
    {!onboardingComplete(onboarding) && <OnboardingChecklist state={onboarding} />}
    {orders.length > 0 && <p className="mb-4 text-sm text-ink-500">{context.workspace.name} · {orders.length.toLocaleString()} Etsy orders · every Etsy fee, shipping, and your costs subtracted per product.</p>}
    <MissingCostsNotice state={onboarding} />
    <form className="mb-5 flex flex-wrap items-end gap-3 rounded-xl border border-brand-100 bg-white p-4 text-sm" method="get">
      <div><label htmlFor="period">Period</label><select id="period" name="period" defaultValue={searchParams.period || "all"}><option value="all">All imported orders</option><option value="month">This month</option><option value="30">Last 30 days</option><option value="custom">Custom range</option></select></div>
      <div><label htmlFor="from">From</label><input id="from" name="from" type="date" defaultValue={searchParams.from} /></div>
      <div><label htmlFor="to">To</label><input id="to" name="to" type="date" defaultValue={searchParams.to} /></div>
      <button className="rounded-full bg-brand-600 px-4 py-2 font-semibold text-white hover:bg-brand-700">Apply</button>
    </form>
    <div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Card><p className="text-sm text-ink-500">Revenue</p><p className="mt-2 text-3xl font-semibold"><Money value={totals.revenue} /></p><p className="mt-1 text-xs text-ink-500">{totals.units.toLocaleString()} units sold</p></Card>
      <Card><p className="text-sm text-ink-500">Fees</p><p className="mt-2 text-3xl font-semibold text-brand-700"><Money value={totals.fees} /></p><p className="mt-1 text-xs text-ink-500">Listings, transaction, processing, ads</p></Card>
      <Card><p className="text-sm text-ink-500">Net profit</p><p className={`mt-2 text-3xl font-semibold ${totals.netProfit < 0 ? "text-red-600" : "text-emerald-700"}`}><Money value={totals.netProfit} /></p><p className="mt-1 text-xs text-ink-500">{totals.margin.toFixed(1)}% true margin</p></Card>
      <Card><p className="text-sm text-ink-500">Shipping + COGS</p><p className="mt-2 text-3xl font-semibold"><Money value={totals.shipping + totals.materials + totals.labor + totals.packaging} /></p><p className="mt-1 text-xs text-ink-500">Estimated from your settings</p></Card>
    </div>
    <Card className="mb-5"><h2 className="font-semibold">Refunds</h2><p className="mt-1 text-sm text-ink-500">{refunds.length} refunded or cancelled orders excluded from revenue.</p><p className="mt-2 text-2xl font-semibold text-red-600"><Money value={refunds.reduce((sum, order) => sum + order.orderTotal, 0)} /></p></Card>
        <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
      <Card className="min-w-0"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Product profitability</h2><p className="text-sm text-ink-500">Red rows are below your {settings.marginThreshold}% margin threshold.</p></div><Link href="/app/products" className="text-xs font-semibold text-brand-700">Edit costs</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-ink-100 text-xs uppercase tracking-wide text-ink-400"><tr><th className="pb-3">Product</th><th className="pb-3">Units</th><th className="pb-3">Revenue</th><th className="pb-3">Fees</th><th className="pb-3">Profit</th><th className="pb-3">Margin</th><th className="pb-3">Profit/hour</th></tr></thead><tbody>{products.map((product) => <tr key={product.name} className={`border-b border-ink-50 ${product.margin < settings.marginThreshold ? "bg-red-50/50" : ""}`}><td className="py-3"><Link href={`/app/products/${product.id}`} className="font-semibold hover:text-brand-700">{product.name}</Link><span className="ml-2 text-xs text-ink-400">{product.sku}</span></td><td className="py-3">{product.units}</td><td className="py-3"><Money value={product.revenue} /></td><td className="py-3"><Money value={product.fees} /></td><td className="py-3 font-semibold"><Money value={product.profit} /></td><td className={`py-3 font-semibold ${product.margin < settings.marginThreshold ? "text-red-600" : "text-emerald-700"}`}>{product.margin.toFixed(1)}%</td><td className="py-3 font-semibold">{product.profitPerHour == null ? "—" : fmtHour(product.profitPerHour)}</td></tr>)}</tbody></table>{!products.length && <p className="rounded-xl bg-ink-50 p-4 text-sm text-ink-500">Load the demo shop or import your Etsy CSVs to see product margins.</p>}</div></Card>
      <div className="space-y-5"><Card><h2 className="font-semibold">Needs attention</h2><div className="mt-3 space-y-3 text-sm">{lowMargin.slice(0, 5).map((product) => <Link href={`/app/products/${product.id}`} key={`m-${product.id}`} className="flex items-center justify-between"><span className="truncate pr-3">{product.name}</span><span className="shrink-0 rounded-full bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-700">{product.margin.toFixed(1)}% margin</span></Link>)}{reorder.slice(0, 5).map((product) => <Link href={`/app/products/${product.id}`} key={`s-${product.id}`} className="flex items-center justify-between"><span className="truncate pr-3">{product.name}</span><span className="shrink-0 rounded-full bg-amber-100 px-2 py-0.5 text-xs font-semibold text-amber-700">{product.stockOnHand} left</span></Link>)}{!lowMargin.length && !reorder.length && <p className="text-ink-500">{products.length ? "No low-margin or low-stock products right now." : "Alerts appear once orders are imported."}</p>}</div></Card><Card><h2 className="font-semibold">Worst 5 products</h2><div className="mt-3 space-y-3">{sorted.slice(0, 5).map((product) => <Link href={`/app/products/${product.id}`} key={product.id} className="flex items-center justify-between text-sm"><span className="truncate pr-3">{product.name}</span><span className="font-semibold text-red-600">{product.margin.toFixed(1)}%</span></Link>)}</div></Card><Card><h2 className="font-semibold">Best 5 products</h2><div className="mt-3 space-y-3">{sorted.slice(-5).reverse().map((product) => <Link href={`/app/products/${product.id}`} key={product.id} className="flex items-center justify-between text-sm"><span className="truncate pr-3">{product.name}</span><span className="font-semibold text-emerald-700">{product.margin.toFixed(1)}%</span></Link>)}</div></Card><Card><h2 className="font-semibold">Best return on time</h2><div className="mt-3 space-y-3">{byHour.map((product) => <Link href={`/app/products/${product.id}`} key={product.id} className="flex items-center justify-between text-sm"><span className="truncate pr-3">{product.name}</span><span className="font-semibold text-emerald-700">{fmtHour(product.profitPerHour!)}/hr</span></Link>)}{!byHour.length && <p className="text-sm text-ink-500">Add labor minutes to your products to see profit per hour.</p>}</div></Card></div>
    </div>
  </Shell>;
}
