import Link from "next/link";
import { loadDemoShopAction, toggleOffsiteAction } from "@/app/actions";
import { ActionForm } from "@/components/action-form";
import { Card, Money, Notice, Shell } from "@/components/shell";
import { shellUser } from "@/lib/auth";
import { getDashboard } from "@/lib/queries";

export default async function DashboardPage({ searchParams: searchParamsPromise }: { searchParams: Promise<{ period?: string; from?: string; to?: string; verified?: string }> }) {
  const searchParams = await searchParamsPromise;
  const data = await getDashboard(searchParams);
  const { totals, products, orders, refunds, settings, context } = data;
  const user = shellUser(context);
  const sorted = [...products].sort((a, b) => a.margin - b.margin);
  return <Shell title="Know what you actually keep" user={user}>
    {searchParams.verified === "1" && <Notice kind="success">Email confirmed. Your workspace is ready.</Notice>}
    {!user.subscribed && <Notice kind="error">Your trial has ended. Dashboards stay visible, but imports and edits are paused until you <Link href="/app/billing" className="font-semibold underline">start a subscription</Link>.</Notice>}
    <div className="mb-4 flex flex-col justify-between gap-4 rounded-2xl bg-violet-950 p-6 text-white sm:flex-row sm:items-center">
      <div><p className="text-sm text-violet-200">{context.workspace.name} · {orders.length ? `${orders.length} Etsy orders in this workspace` : "Ready for your Etsy exports"}</p><h2 className="mt-1 text-2xl font-semibold">Profit without the fragile spreadsheet.</h2><p className="mt-2 max-w-xl text-sm text-violet-100">Every Etsy fee, material, labor, and shipping cost in one calm view.</p></div>
      {!orders.length && <ActionForm action={loadDemoShopAction} submitLabel="Load demo shop" submitClassName="rounded-lg bg-white px-4 py-2 text-center text-sm font-semibold text-violet-900 hover:bg-violet-50" inline />}
    </div>
    <form className="mb-5 flex flex-wrap items-end gap-3 rounded-xl border border-violet-100 bg-white p-4 text-sm" method="get">
      <div><label htmlFor="period">Period</label><select id="period" name="period" defaultValue={searchParams.period || "all"}><option value="all">All imported orders</option><option value="month">This month</option><option value="30">Last 30 days</option><option value="custom">Custom range</option></select></div>
      <div><label htmlFor="from">From</label><input id="from" name="from" type="date" defaultValue={searchParams.from} /></div>
      <div><label htmlFor="to">To</label><input id="to" name="to" type="date" defaultValue={searchParams.to} /></div>
      <button className="rounded-lg bg-violet-600 px-4 py-2 font-semibold text-white">Apply</button>
    </form>
    <div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Card><p className="text-sm text-slate-500">Revenue</p><p className="mt-2 text-3xl font-semibold"><Money value={totals.revenue} /></p><p className="mt-1 text-xs text-slate-500">{totals.units.toLocaleString()} units sold</p></Card>
      <Card><p className="text-sm text-slate-500">Fees</p><p className="mt-2 text-3xl font-semibold text-violet-700"><Money value={totals.fees} /></p><p className="mt-1 text-xs text-slate-500">Listings, transaction, processing, ads</p></Card>
      <Card><p className="text-sm text-slate-500">Net profit</p><p className={`mt-2 text-3xl font-semibold ${totals.netProfit < 0 ? "text-red-600" : "text-emerald-700"}`}><Money value={totals.netProfit} /></p><p className="mt-1 text-xs text-slate-500">{totals.margin.toFixed(1)}% true margin</p></Card>
      <Card><p className="text-sm text-slate-500">Shipping + COGS</p><p className="mt-2 text-3xl font-semibold"><Money value={totals.shipping + totals.materials + totals.labor + totals.packaging} /></p><p className="mt-1 text-xs text-slate-500">Estimated from your settings</p></Card>
    </div>
    <Card className="mb-5"><h2 className="font-semibold">Refunds</h2><p className="mt-1 text-sm text-slate-500">{refunds.length} refunded or cancelled orders excluded from revenue.</p><p className="mt-2 text-2xl font-semibold text-red-600"><Money value={refunds.reduce((sum, order) => sum + order.orderTotal, 0)} /></p></Card>
        <div className="grid gap-5 lg:grid-cols-[1fr_320px]">
      <Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Product profitability</h2><p className="text-sm text-slate-500">Red rows are below your {settings.marginThreshold}% margin threshold.</p></div><Link href="/app/products" className="text-xs font-semibold text-violet-700">Edit costs</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th className="pb-3">Product</th><th className="pb-3">Units</th><th className="pb-3">Revenue</th><th className="pb-3">Fees</th><th className="pb-3">Profit</th><th className="pb-3">Margin</th><th className="pb-3">Profit/hour</th></tr></thead><tbody>{products.map((product) => <tr key={product.name} className={`border-b border-slate-50 ${product.margin < settings.marginThreshold ? "bg-red-50/50" : ""}`}><td className="py-3"><Link href={`/app/products/${product.id}`} className="font-semibold hover:text-violet-700">{product.name}</Link><span className="ml-2 text-xs text-slate-400">{product.sku}</span></td><td className="py-3">{product.units}</td><td className="py-3"><Money value={product.revenue} /></td><td className="py-3"><Money value={product.fees} /></td><td className="py-3 font-semibold"><Money value={product.profit} /></td><td className={`py-3 font-semibold ${product.margin < settings.marginThreshold ? "text-red-600" : "text-emerald-700"}`}>{product.margin.toFixed(1)}%</td><td className="py-3 font-semibold">{product.profitPerHour == null ? "—" : `$${product.profitPerHour.toFixed(2)}`}</td></tr>)}</tbody></table>{!products.length && <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Load the demo shop or import your Etsy CSVs to see product margins.</p>}</div></Card>
      <div className="space-y-5"><Card><h2 className="font-semibold">Worst 5 products</h2><div className="mt-3 space-y-3">{sorted.slice(0, 5).map((product) => <Link href={`/app/products/${product.id}`} key={product.id} className="flex items-center justify-between text-sm"><span className="truncate pr-3">{product.name}</span><span className="font-semibold text-red-600">{product.margin.toFixed(1)}%</span></Link>)}</div></Card><Card><h2 className="font-semibold">Best 5 products</h2><div className="mt-3 space-y-3">{sorted.slice(-5).reverse().map((product) => <Link href={`/app/products/${product.id}`} key={product.id} className="flex items-center justify-between text-sm"><span className="truncate pr-3">{product.name}</span><span className="font-semibold text-emerald-700">{product.margin.toFixed(1)}%</span></Link>)}</div></Card><Card><h2 className="font-semibold">Best return on time</h2><div className="mt-3 space-y-3">{[...products].filter((product) => product.profitPerHour != null).sort((a, b) => (b.profitPerHour ?? 0) - (a.profitPerHour ?? 0)).slice(0, 5).map((product) => <Link href={`/app/products/${product.id}`} key={product.id} className="flex items-center justify-between text-sm"><span className="truncate pr-3">{product.name}</span><span className="font-semibold text-emerald-700">${product.profitPerHour!.toFixed(2)}/hr</span></Link>)}</div></Card></div>
    </div>
    <Card className="mt-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Offsite ads attribution</h2><p className="text-sm text-slate-500">Flag orders Etsy attributed to offsite ads. The settings fallback is used only when none are flagged.</p></div><Link href="/app/settings" className="text-xs font-semibold text-violet-700">Configure fallback</Link></div><div className="mt-4 max-h-64 overflow-auto">{orders.slice(0, 12).map((order) => <div key={order.id} className="flex items-center justify-between border-b border-slate-50 py-2 text-sm"><span>{order.externalId} · {order.buyer}</span><form action={toggleOffsiteAction} className="flex items-center gap-2"><input type="hidden" name="orderId" value={order.id} /><label className="flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" name="offsiteAds" defaultChecked={order.offsiteAdsAttributed} /> Offsite ads attributed</label><button className="rounded-full bg-violet-100 px-3 py-1 text-xs font-semibold text-violet-700">Save</button></form></div>)}</div></Card>
  </Shell>;
}
